apiVersion: v1
kind: Secret
metadata:
  name: mongo-config-db-credentials-secrets
  namespace: mongo
type: Opaque
data:
  mongo-initdb-root-username : bW9uZ28K      # base64-encoded value of "mongo"
  mongo-initdb-root-password : bW9uZ28K      # base64-encoded value of "mongo"
