apiVersion: v1 #API VERSION NEEDED DEPENDING ON API GROUP.
kind: Service # Kind is service 

metadata:
  name: mongo-express-service # Name of service
  namespace: mongo
spec:
  selector:     # Selects the pods with label 
    app: mongoexpress  
  type: NodePort  # type can be clusterip , nodeport , loadbalancer
  ports:    # port exposing/listening on and target port to send/forward request on
    - name: http
      protocol: TCP
      port: 8081 #port field in a Service specifies the port number on which the Service will listen for incoming traffic within the cluster
      targetPort: 8081 # targetPort is the port number on the Pods to which traffic from the Service is forwarded.
      nodePort: 32601 # Host port on which we can access service externally
  
